### ISSUE TITLE
list offiles and folders say "ironman"

### ISSUE THREAD

**Issue by gosfand** [ybrs/putio-xbmc-v2#4]
just installed your plugin for   frodo to support apiv2 and it lists all file names as "Ironman"

**Comment by mttch** [comment]
I have the same problem, found a way to fix it.

In default.py, comment out line 72: listItem.setInfo('video', {'Title': 'Ironman', 'Genre': 'Science Fiction'})

**Comment by ybrs** [comment]
I really dont know why but that line wasn't causing trouble on my system. 

Anyways, fixed it in the latest commit, 444a77d64d266ce13f6fadd6233affd737ee52bd

Thank you
